version: '3'

services:
  micro-auth:
    volumes:
      - ./api:/app/api
      - ./tests:/app/tests
    build:
      dockerfile: ./Dockerfile-testing
    environment:
      - HS_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MC_HOST_hydroshare=http://minioadmin:minioadmin@minio:9000
    links:
      - postgres
      - redis
      - minio
    ports:
      - 8001:8001
    restart: on-failure
  postgres:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./tests/init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    restart: on-failure
    volumes:
      - redis_data:/data
  minio:
    image: minio/minio
    platform: linux/amd64
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - "9000"
      - "9001"
    volumes:
      - minio_data_vol:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT: "false"
      MINIO_SCANNER_SPEED: "fastest"
      MINIO_POLICY_PLUGIN_URL: "http://micro-auth/minio/authorization/"
    command: server --console-address ":9001" /data

volumes:
  postgres_data:
  redis_data:
  minio_data_vol:
