version: '3'

volumes:
  mongo_data:
    driver: local

services:
  api:
    volumes:
      - ./api:/app/api
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 80:80
    restart: on-failure